version: '2'

services:
  demo-client:
    image: demo-client
    container_name: demo-client
    depends_on:
      - demo-server
      - tracing-server
    ports:
      - 8080:8080
  demo-server:
    image: demo-server
    container_name: demo-server
    ports:
      - 9090:9090
  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    mem_limit: 512M
    environment:
    - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
     - 9411:9411

  grafana-server:
    image: grafana/grafana
    container_name: grafana-server
    mem_limit: 256M
    ports:
    - 3000:3000

  prometheus-server:
    image: prom/prometheus
    container_name: prometheus-server
    mem_limit: 256M
    ports:
    - 9091:9090
